// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-BUhhIGAiNmrydou1kcrz_Xwv0ub82E',
    appId: '1:18992756375:web:1f32c93875a9448eca5bd2',
    messagingSenderId: '18992756375',
    projectId: 'pg1boris',
    authDomain: 'pg1boris.firebaseapp.com',
    storageBucket: 'pg1boris.appspot.com',
    measurementId: 'G-TQ775CJ789',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEuVRTmLpFWU2MAjbq3FZ-_pOB9XMu5qw',
    appId: '1:18992756375:android:e6a47386c6f9ca86ca5bd2',
    messagingSenderId: '18992756375',
    projectId: 'pg1boris',
    storageBucket: 'pg1boris.appspot.com',
  );

}